name: Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-go
            git

      - name: Build 403Cord Installer
        shell: msys2 {0}
        run: |
          export GOROOT=/mingw64/lib/go
          export GOPATH=/mingw64
          export PATH=/mingw64/bin:$PATH
          
          go mod tidy
          
          go install github.com/tc-hib/go-winres@latest
          /mingw64/bin/go-winres make
          
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -v -tags static \
            -ldflags "-s -w -H=windowsgui -extldflags=-static -X '403cordinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)'" \
            -o 403CordInstaller.exe

      - name: Upload Installer .exe
        uses: actions/upload-artifact@v4
        with:
          name: 403CordInstaller-Windows
          path: 403CordInstaller.exe
